version: "3.9"  # optional since v1.27.0
services:
  carrental:
    image: carrental_webapi
    container_name: carrental
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql-server-2019
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Mssql.2019.Docker